version: '3.3'

services:
  db:
    container_name: database
    image: mariadb  
    ports: 
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    container_name: wordpress 
    depends_on:
      - db
    ports:
      - "80:80"    
    volumes:
      - wp_data:/var/wwww/html
    links: 
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress      
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on: 
      - db
    restart: always
    ports:
      - "8080:80"
   
volumes:
  db_data: {}
  wp_data: {}
